module.exports.msg = function (code) {
    const codeArr = {
      /* For Global Use */
      "MSG001": "Invalid request data!",
      "MSG002": "Something went wrong! Please try again.",
      "MSG003": "Unauthorized user!",
      "MSG004": "Registration complete",
      "MSG005": "User logged in successfully!",
      "MSG006": "Record Found successfully!",
      "MSG007": "Record Not Found!",
      "MSG008": "Invalid email or password",
      "MSG009": "Account already exist with same Email.",
      "MSG010": "dur profile updated successfully.",
      "MSG011": "The email address that you've entered doesn't match any account",
      "MSG012": "Record updated successfully!",
      "MSG013": "Image should be PNG | JPG | JPEG Format.",
      "MSG014": "File uploaded successfully.",
      "MSG015": "Record deleted successfully.",
      "MSG016": "Your Current Password is incorrect.",
      "MSG017": "Password changed successfully.",
      "MSG018": "Reset password link has been sent successfully. Please check your email.",
      "MSG019": "Reset password link has been expired.",
      "MSG020": "Your account is in-active. please verify your email and phone.",
      "MSG021": "Email verification link has been expired.",
      "MSG022": "Your account has been verified successfully.",
      "MSG023": "Email address does not exist.",
      "MSG024": "Record added successfully.",
      "MSG025": "Unable to send Link to your email.",
      "MSG026": "Unable to reset your password. Please try again.",
      "MSG027": "Unable to Validate Password or Email.",
      "MSG028": "Record successfully updated.",
      "MSG029": "Success.",
      "MSG030": "Image format should be .png, .jpg or .jpeg.",
      "MSG031": "Record created successfully.",
      "MSG032": "Email is not verified",
      "MSG033": "Mobile Number is not verified",
      "MSG034": "This Language Already Exists.",
      "MSG035": "Work Information Updated.",
      "MSG036": "Emergency Contact Added.",
      "MSG037": "Emergency Contact Updated.",
      "MSG038": "Emergency Contact Deleted",
    }
  
    return (typeof codeArr[code] !== "undefined" ? codeArr[code] : "");
  }